### PR TITLE
Update serde dependency to 1.0

### PR DESCRIPTION
**Pull request by DenisKolodin**
Significant (de)serialization improvements.

### CODE REVIEW

**Comment by mitchmindtree** [comment]
Hey thanks for this @DenisKolodin!

Originally the main reason I was manually implementing the Serialize/Deserialize traits was because the `derive` syntax was not available on stable rust. Now that the derive macros *do* work on stable, maybe we would be better off removing the manual impls in favour of using derive?

**Comment by DenisKolodin** [comment]
It's really better if possible to keep the format. I'll update this according the tests.

**Comment by DenisKolodin** [comment]
I've moved the solution to the derived serialization, but keep tests the same.
I think we should save both commits, because they contains different approaches and could be useful for historic reasons.

**Comment by DenisKolodin** [comment]
@mitchmindtree Any progress on this?

**Comment by mitchmindtree** [comment]
So sorry about the delay on this!

Yes this looks fine, thanks for taking the time to submit a PR!

**Pull request merged**
